version: '3'

services:
  pyrfc:
    container_name: container_pyrfc
    build:
      context: .
      dockerfile: ./compose/pyrfc/Dockerfile
    volumes:
      - .:/project
    #environment:
    image: image_pyrfc:latest
    #env_file: .env
    #ports:
    #  - "8888:8888"
    #stdin_open: true
    #tty: true
    #depends_on:
    #- mysql
    #command: ["python", "app/manage.py", "runserver", "0.0.0.0:8888"]
  falcon:
    container_name: container_falcon
    build:
      context: .
      dockerfile: ./compose/falcon/Dockerfile
    volumes:
      - .:/project
    ports:
      - "80:80"