version: '3'

services:
  pyrfc:
    container_name: container_pyrfc
    build:
      context: .
      dockerfile: ./compose/pyrfc/Dockerfile
    volumes:
      - .:/project
    image: image_pyrfc:latest
    ports:
      - "80:80"